l_korean:
 SETTING_AUTOSAVE_TO_CLOUD: "클라우드에 자동 저장"
 SETTING_SAVE_FILE_FORMAT: "기본 저장 형식"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "본 옵션은 철인, 클라우드, 디버그 모드에서만 수정할 수 있습니다."
 OPTION_SAVE_FILE_TEXT: "텍스트"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "잠긴 텍스트"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "잠긴 2진수"
 SETTING_TOOLTIP_MODE: "툴팁 모드"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\n툴팁 고정 방식을 설정합니다.\n   #b 마우스 움직임#! - 마우스 커서를 툴팁으로 가져가면 고정합니다.\n   #b 타이머 고정식#! - 일정한 시간이 지나면 고정합니다.\n   #b 동작 고정식#! - 마우스 가운데 버튼으로 고정합니다.\n   #b 타이머 또는 동작 고정식#! - 타이머 고정식 또는 동작 고정식을 사용할 수 있습니다."
 SETTING_TOOLTIP_MODE_NO_LOCK: "잠금 없음"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "마우스 움직임"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "동작 고정식 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "타이머 고정식 (마우스 앵커)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "동작 고정식"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "타이머 고정식"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "타이머 또는 동작 고정식"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\n툴팁에 커서를 올렸을 때 몇 초 후에 툴팁을 표시할지 설정합니다."
 SETTING_TOOLTIP_DELAY: "지연 시간 표시"
 SETTING_TOOLTIP_UNLOCK_TIME: "잠금 해제 지연 시간"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\n툴팁이 잠금 해제되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_LOCK_TIME: "잠금 지연 시간"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\n툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "잠금 후 열림 지연 시간"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\n이미 다른 툴팁이 표시된 상태에서 툴팁이 잠금되기까지 걸리는 지연 시간을 설정합니다."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "고급"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "일반"
 SETTINGS_CATEGORY_SFX: "효과음"
 SETTINGS_CATEGORY_MFX: "음악"
 SETTINGS_CATEGORY_LANGUAGE: "언어"
 SETTINGS_CATEGORY_SAVE_GAMES: "저장된 게임"
 SETTINGS_CATEGORY_TOOLTIPS: "툴팁 설정"
 SETTINGS_CATEGORY_MAP_CONTROLS: "지도 조작"
 SETTINGS_CATEGORY_MAPMODES: "지도 모드"
 SETTING_SHADER_QUALITY: "셰이더 품질"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T 셰이더 품질\n#!여러 셰이더와 효과의 품질을 결정합니다.\n\n#T 높음:#! 퍼포먼스는 저하되지만 일부 셰이더 효과의 품질이 향상됩니다.\n\n#T 보통:#! 의도한 대로 그래픽 경험을 할 수 있는 기본 설정입니다.\n\n#T 낮음:#! 사양이 낮은 기기를 위한 설정으로, 시각 품질이 낮아지므로 권장되는 옵션은 아닙니다. 그래픽 퍼포먼스 향상을 위해 각종 셰이더가 단순화됩니다."
 SETTING_SHOW_NUDITY: "누드 표시"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\n인물 누드를 표시할지 설정합니다."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "초상화"
 SETTING_SOUNDTRACK: "배경 음악"
 SETTING_SOUNDTRACK_TOOLTIP: "일반 배경 음악"
 SETTING_MUSIC_STINGERS: "음악 스팅"
 SETTING_MUSIC_STINGERS_TOOLTIP: "게임플레이에 잔재미를 더해주는 짤막한 음악입니다."
#Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "음악"
 SETTING_AMBIENT: "환경음"
 SETTING_MUSIC_TOOLTIP: "#T 음악 음량\n#!음악의 음량을 설정합니다."
 SETTING_AMBIENT_TOOLTIP: "#T 환경음 음량\n#!환경음의 음량을 설정합니다."
 SETTING_MAP_TOOLTIP_DELAY: "지도 툴팁 지연 시간"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\n지도 툴팁을 표시하기까지 걸리는 지연 시간을 설정합니다."
 SETTING_MAP_MODE_DELAY: "지도 모드 지연 시간"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "새로운 지도 모드로 전환하기까지 걸리는 지연 시간을 설정합니다. (초 단위)"
 SETTING_MAP_MODE_FADE_IN: "지도 모드 페이드 인"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "기존 지도 모드가 페이드 아웃된 후 새로운 지도 모드가 페이드 인되기까지 걸리는 시간을 설정합니다. (초 단위)"
 SETTING_MAP_MODE_FADE_OUT: "지도 모드 페이드 아웃"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "새로운 지도 모드를 적용한 후 현재 지도 모드가 페이드 아웃되기까지 걸리는 시간을 설정합니다. (초 단위)"
 SETTING_OCCUPATION_STRIPES: "줄무늬 점유 시각 효과"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\n국기 텍스처 대신 색상 줄무늬를 지도에서 점유의 시각적 표시로 사용합니다."
 color_blind_mode_test: "테스트"
