l_french:
 SETTING_AUTOSAVE_TO_CLOUD: "Sauvegarde auto sur le Cloud"
 SETTING_SAVE_FILE_FORMAT: "Format de sauvegarde par défaut"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Cette option est ignorée en mode Ironman, Cloud et Debug"
 OPTION_SAVE_FILE_TEXT: "Texte"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Texte condensé"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Binaire condensé"
 SETTING_TOOLTIP_MODE: "Mode infobulle"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nComment les infobulles doivent se verrouiller ?\n   #b Selon la souris#! - se verrouille si vous déplacez la souris vers l’infobulle.\n   #b Selon le temps#! - se verrouille après un temps défini.\n   #b Selon l’action#! - se verrouille via le bouton central de la souris.\n   #b Selon le temps ou l’action#! - se verrouille soit selon le temps soit selon l’action."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Pas de verrouillage"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Selon la souris"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Verrouillage de l’action (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Verrouillage du temps (ancrage souris)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Selon l’action"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Selon le temps"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Selon le temps ou l’action"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nDéfinit le délai avant que l’infobulle n’apparaisse lors du survol d’un élément avec une infobulle."
 SETTING_TOOLTIP_DELAY: "Afficher le délai"
 SETTING_TOOLTIP_UNLOCK_TIME: "Délai de déverrouillage"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nDéfinit le délai avant le déverrouillage des infobulles."
 SETTING_TOOLTIP_LOCK_TIME: "Délai de verrouillage"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nDéfinit le délai avant le verrouillage des infobulles."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Délai de verrouillage si ouvert"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nDéfinit le délai avant le verrouillage des infobulles lorsqu’une autre infobulle est déjà ouverte."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avancé"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Général"
 SETTINGS_CATEGORY_SFX: "Effets sonores"
 SETTINGS_CATEGORY_MFX: "Musique"
 SETTINGS_CATEGORY_LANGUAGE: "Langue"
 SETTINGS_CATEGORY_SAVE_GAMES: "Sauvegardes"
 SETTINGS_CATEGORY_TOOLTIPS: "Paramètres des infobulles"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Contrôles de carte"
 SETTINGS_CATEGORY_MAPMODES: "Modes de carte"
 SETTING_SHADER_QUALITY: "Qualité des nuanceurs"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Qualité des nuanceurs\n#!Permet de régler la qualité des différents effets et nuanceurs.\n\n#T Élevée :#! améliore la qualité des nuanceurs, mais réduit les performances.\n\n#T Moyenne :#! paramètres par défaut pour des graphismes optimaux.\n\n#T Faible :#! plusieurs nuanceurs sont simplifiés afin de réduire la qualité des graphismes et d’améliorer les performances pour les machines moins puissantes."
 SETTING_SHOW_NUDITY: "Afficher la nudité"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDéfinit si les personnages peuvent être affichés nus."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Portraits"
 SETTING_SOUNDTRACK: "Musique de fond"
 SETTING_SOUNDTRACK_TOOLTIP: "Musique de fond générale"
 SETTING_MUSIC_STINGERS: "Phrases musicales"
 SETTING_MUSIC_STINGERS_TOOLTIP: "De courtes phrases musicales pour améliorer la jouabilité"
#Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Musique"
 SETTING_AMBIENT: "Ambiance"
 SETTING_MUSIC_TOOLTIP: "#T Volume de la musique\n#!Permet de régler le volume de la musique."
 SETTING_AMBIENT_TOOLTIP: "#T Volume d’ambiance\n#!Permet de régler le volume des sons d’ambiance."
 SETTING_MAP_TOOLTIP_DELAY: "Délai de l’infobulle de la carte"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nDéfinit le délai avant l’affichage de l’infobulle de la carte."
 SETTING_MAP_MODE_DELAY: "Délai du mode carte"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Délai avant de passer à un autre mode de carte, en secondes."
 SETTING_MAP_MODE_FADE_IN: "Temps du nouveau mode de carte"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Temps pour qu’un nouveau mode de carte apparaisse après la disparition de l’ancien, en secondes."
 SETTING_MAP_MODE_FADE_OUT: "Temps de l’ancien mode de carte"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Temps nécessaire pour que le mode de carte actuel disparaisse lorsqu’un nouveau mode de carte doit être appliqué, en secondes."
 SETTING_OCCUPATION_STRIPES: "Bandes de couleur pour l’occupation"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nAfficher des bandes de couleur pour signaler l’occupation sur la carte plutôt que les textures de drapeau du pays"
 color_blind_mode_test: "Test"
