l_german:
 SETTING_AUTOSAVE_TO_CLOUD: "In Cloud autospeichern"
 SETTING_SAVE_FILE_FORMAT: "Standard-Speicherformat"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Diese Option wird im Ironman-, Cloud- und Debug-Modus überschrieben"
 OPTION_SAVE_FILE_TEXT: "Text"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Gezippter Text"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Gezipptes Binary"
 SETTING_TOOLTIP_MODE: "Tooltip-Modus"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nLegt fest, wie die Tooltip-Locks aktiviert werden:\n   #b Maustendenz#! – Wird aktiviert, wenn man die Maus auf den Tooltip zubewegt.\n   #b Timer-Lock#! – Wird nach einer bestimmten Frist aktiviert.\n   #b Aktions-Lock#! – Wird mit der mittleren Maustaste aktiviert.\n   #b Timer- oder Aktions-Lock#! – Kann entweder Timer-Lock oder Aktions-Lock verwenden"
 SETTING_TOOLTIP_MODE_NO_LOCK: "Kein Lock"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Maustendenz"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Aktions-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Timer-Lock (Mausanker)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Aktions-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Timer-Lock"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Timer- oder Aktions-Lock"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, ehe der Tooltip angezeigt wird, wenn der Mauszeiger auf einem Element mit Tooltip ist."
 SETTING_TOOLTIP_DELAY: "Verzögerung anzeigen"
 SETTING_TOOLTIP_UNLOCK_TIME: "Freischaltungsverzögerung"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips freigeschaltet werden."
 SETTING_TOOLTIP_LOCK_TIME: "Lock-Verzögerung"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Lock-Öffnungsverzögerung"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nLegt die Verzögerung fest, bis Tooltips verriegelt werden, während ein anderer Tooltip geöffnet ist."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Fortgeschritten"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "Allgemein"
 SETTINGS_CATEGORY_SFX: "Soundeffekte"
 SETTINGS_CATEGORY_MFX: "Musik"
 SETTINGS_CATEGORY_LANGUAGE: "Sprache"
 SETTINGS_CATEGORY_SAVE_GAMES: "Spielstände"
 SETTINGS_CATEGORY_TOOLTIPS: "Tooltip-Einstellungen"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Kartensteuerung"
 SETTINGS_CATEGORY_MAPMODES: "Kartenmodi"
 SETTING_SHADER_QUALITY: "Shader-Qualität"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Shader-Qualität\n#!Bestimmt die Qualität verschiedener Shader und Effekte.\n\n#T Hoch:#! Verbessert die Qualität einiger Shader-Effekte auf Kosten der Leistung.\n\n#T Mittel:#! Standardeinstellung für die intendierte Grafikerfahrung.\n\n#T Niedrig:#! Diese Einstellung ist für Low-End-Computer gedacht und wird aufgrund des Verlusts an visueller Qualität nicht empfohlen. Eine Reihe von Shadern wird vereinfacht, um die Grafikleistung zu verbessern."
 SETTING_SHOW_NUDITY: "Nacktheit anzeigen"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nLegt fest, ob Charaktere nackt gezeigt werden können."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Porträts"
 SETTING_SOUNDTRACK: "Hintergrundmusik"
 SETTING_SOUNDTRACK_TOOLTIP: "Allgemeine Hintergrundmusik"
 SETTING_MUSIC_STINGERS: "Musikanzeiger"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Kurze musikalische Phrasen, die das Gameplay unterstützen."
#Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Musik"
 SETTING_AMBIENT: "Umgebung"
 SETTING_MUSIC_TOOLTIP: "#T Musiklautstärke\n#!Steuert die Lautstärke der Hintergrundmusik."
 SETTING_AMBIENT_TOOLTIP: "#T Umgebungslautstärke\n#!Steuert die Lautstärke der Umgebungsatmosphäre."
 SETTING_MAP_TOOLTIP_DELAY: "Karten-Tooltip-Verzögerung"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nLegt die Verzögerung fest, bis Karten-Tooltips erscheinen."
 SETTING_MAP_MODE_DELAY: "Kartenmodus-Verzögerung"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Verzögerung vor dem Wechsel in einen neuen Kartenmodus (in Sekunden)"
 SETTING_MAP_MODE_FADE_IN: "Kartenmodus-Einblendung"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Zeit, bis ein neuer Kartenmodus eingeblendet wird, nachdem ein alter ausgeblendet wurde (in Sekunden)"
 SETTING_MAP_MODE_FADE_OUT: "Kartenmodus-Ausblendung"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Zeit, bis ein neuer Kartenmodus ausgeblendet wird, nachdem ein neuer angewendet wurde und die Kartenmodus-Verzögerung verstrichen ist (in Sekunden)"
 SETTING_OCCUPATION_STRIPES: "Schraffierte Besatzungsanzeigen"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nFarbige Streifen als Besatzungsanzeige auf der Karte anstelle von Landesflaggentexturen aktivieren"
 color_blind_mode_test: "Test"
