l_spanish:
 SETTING_AUTOSAVE_TO_CLOUD: "Guardado automático en la nube"
 SETTING_SAVE_FILE_FORMAT: "Formato de guardado por defecto"
 SETTING_SAVE_FILE_FORMAT_TOOLTIP: "Esta opción se anula en los modos de Ironman, guardado en la nube y depuración."
 OPTION_SAVE_FILE_TEXT: "Texto"
 OPTION_SAVE_FILE_ZIP_TEXT_ALL: "Texto comprimido"
 OPTION_SAVE_FILE_ZIP_BINARY_ALL: "Código en binario comprimido"
 SETTING_TOOLTIP_MODE: "Modo ayuda emergente"
 SETTING_TOOLTIP_MODE_TOOLTIP: "#T $SETTING_TOOLTIP_MODE$#!\nElige cómo deben bloquearse las ayudas emergentes:\n   #b Tendencia del ratón#! - Se bloquea si se mueves el ratón hacia la ayuda emergente.\n   #b Bloqueo temporal#! - Se bloquea después de un tiempo determinado.\n   #b Bloqueo por acción#! - Se bloquea con el botón central del ratón.\n   #b Bloqueo temporal o por acción#! - Se pueden utilizar el bloqueo temporal o el bloqueo por acción."
 SETTING_TOOLTIP_MODE_NO_LOCK: "Sin bloqueo"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY: "Tendencia del ratón"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_MOUSE_ANCHOR: "Bloqueo por acción (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_MOUSE_ANCHOR: "Bloqueo temporal (anclar ratón)"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_WIDGET_ANCHOR: "Bloqueo por acción"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_WIDGET_ANCHOR: "Bloqueo temporal"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_OR_ACTION_WIDGET_ANCHOR: "Bloqueo temporal o por acción"
 SETTING_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_TOOLTIP_DELAY$#!\nEstablece el tiempo que ha de transcurrir antes de que se muestre la ayuda emergente al pasar por encima de un elemento que incluya una."
 SETTING_TOOLTIP_DELAY: "Mostrar retardo"
 SETTING_TOOLTIP_UNLOCK_TIME: "Retardo de desbloqueo"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nEstablece el tiempo que tardan en desbloquearse las ayudas emergentes."
 SETTING_TOOLTIP_LOCK_TIME: "Retardo de bloqueo"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP: "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED: "Retardo de bloqueo abierto"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP: "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nEstablece el tiempo que tardan en bloquearse las ayudas emergentes cuando ya se está mostrando otra ayuda."
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS: "Avanzada"
 SETTINGS_CATEGORY_AUDIO_GENERAL: "General"
 SETTINGS_CATEGORY_SFX: "Efectos de sonido"
 SETTINGS_CATEGORY_MFX: "Música"
 SETTINGS_CATEGORY_LANGUAGE: "Idioma"
 SETTINGS_CATEGORY_SAVE_GAMES: "Partidas guardadas"
 SETTINGS_CATEGORY_TOOLTIPS: "Ajustes de la ayuda emergente"
 SETTINGS_CATEGORY_MAP_CONTROLS: "Controles de juego"
 SETTINGS_CATEGORY_MAPMODES: "Modos de mapa"
 SETTING_SHADER_QUALITY: "Calidad de los sombreados"
 SETTING_SHADER_QUALITY_TOOLTIP: "#T Calidad de los sombreados\n#!Determina la calidad de los diferentes sombreados y efectos.\n\n#T Alta:#! mejora la calidad de algunos efectos de sombreado a costa del rendimiento.\n\n#T Media:#! ajuste por defecto para disfrutar de la experiencia gráfica esperada.\n\n#T Baja:#! esta opción es perfecta para dispositivos de gama baja. No la recomendamos debido a la pérdida de calidad visual. Se simplifican diferentes sombreados para mejorar el rendimiento gráfico."
 SETTING_SHOW_NUDITY: "Mostrar desnudos"
 SETTING_SHOW_NUDITY_TOOLTIP: "#T $SETTING_SHOW_NUDITY$#!\nDetermina si los personajes pueden aparecer desnudos."
 SETTINGS_CATEGORY_GAME_PORTRAITS: "Retratos"
 SETTING_SOUNDTRACK: "Música de fondo"
 SETTING_SOUNDTRACK_TOOLTIP: "Música de fondo general"
 SETTING_MUSIC_STINGERS: "Stingers musicales"
 SETTING_MUSIC_STINGERS_TOOLTIP: "Frases musicales cortas para mejorar la partida"
#Audio - These are copies of clausewitz keys due to case sensitivity
 SETTING_MUSIC: "Música"
 SETTING_AMBIENT: "Ambiente"
 SETTING_MUSIC_TOOLTIP: "#T Volumen de la música\n#!Controla el volumen de la música de fondo."
 SETTING_AMBIENT_TOOLTIP: "#T Volumen ambiental\n#!Controla el volumen del ambiente."
 SETTING_MAP_TOOLTIP_DELAY: "Retardo de ayuda emergente del mapa"
 SETTING_MAP_TOOLTIP_DELAY_TOOLTIP: "#T $SETTING_MAP_TOOLTIP_DELAY$#!\nEstablece el tiempo que tarda en aparecer la ayuda emergente del mapa."
 SETTING_MAP_MODE_DELAY: "Retardo del mapa"
 SETTING_MAP_MODE_DELAY_TOOLTIP: "Retardo, en segundos, antes de cambiar a un nuevo modo de mapa."
 SETTING_MAP_MODE_FADE_IN: "Aparición del modo de mapa"
 SETTING_MAP_MODE_FADE_IN_TOOLTIP: "Tiempo, en segundos, que tarda un nuevo modo de mapa en aparecer después de que el anterior desaparezca."
 SETTING_MAP_MODE_FADE_OUT: "Desaparición del modo de mapa"
 SETTING_MAP_MODE_FADE_OUT_TOOLTIP: "Tiempo, en segundos, que tarda el modo de mapa actual en desaparecer en función de su retardo al aplicar un nuevo modo de mapa."
 SETTING_OCCUPATION_STRIPES: "Gráficos de ocupación a rayas"
 SETTING_OCCUPATION_STRIPES_TOOLTIP: "#T $SETTING_OCCUPATION_STRIPES$#!\nActiva rayas de colores como gráficos de ocupación en el mapa en vez de texturas con banderas de países"
 color_blind_mode_test: "Prueba"
